// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: facility.proto

package genprotos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FacilityService_CreateFacility_FullMethodName = "/facility.FacilityService/CreateFacility"
	FacilityService_UpdateFacility_FullMethodName = "/facility.FacilityService/UpdateFacility"
	FacilityService_DeleteFacility_FullMethodName = "/facility.FacilityService/DeleteFacility"
	FacilityService_ListFacility_FullMethodName   = "/facility.FacilityService/ListFacility"
	FacilityService_GetFacility_FullMethodName    = "/facility.FacilityService/GetFacility"
)

// FacilityServiceClient is the client API for FacilityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FacilityServiceClient interface {
	CreateFacility(ctx context.Context, in *CreateFacilityRequest, opts ...grpc.CallOption) (*CreateFacilityResponse, error)
	UpdateFacility(ctx context.Context, in *UpdateFacilityRequest, opts ...grpc.CallOption) (*UpdateFacilityResponse, error)
	DeleteFacility(ctx context.Context, in *DeleteFacilityRequest, opts ...grpc.CallOption) (*DeleteFacilityResponse, error)
	ListFacility(ctx context.Context, in *ListFacilityRequest, opts ...grpc.CallOption) (*ListFacilityResponse, error)
	GetFacility(ctx context.Context, in *GetFacilityRequest, opts ...grpc.CallOption) (*GetFacilityResponse, error)
}

type facilityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFacilityServiceClient(cc grpc.ClientConnInterface) FacilityServiceClient {
	return &facilityServiceClient{cc}
}

func (c *facilityServiceClient) CreateFacility(ctx context.Context, in *CreateFacilityRequest, opts ...grpc.CallOption) (*CreateFacilityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateFacilityResponse)
	err := c.cc.Invoke(ctx, FacilityService_CreateFacility_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *facilityServiceClient) UpdateFacility(ctx context.Context, in *UpdateFacilityRequest, opts ...grpc.CallOption) (*UpdateFacilityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateFacilityResponse)
	err := c.cc.Invoke(ctx, FacilityService_UpdateFacility_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *facilityServiceClient) DeleteFacility(ctx context.Context, in *DeleteFacilityRequest, opts ...grpc.CallOption) (*DeleteFacilityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteFacilityResponse)
	err := c.cc.Invoke(ctx, FacilityService_DeleteFacility_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *facilityServiceClient) ListFacility(ctx context.Context, in *ListFacilityRequest, opts ...grpc.CallOption) (*ListFacilityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFacilityResponse)
	err := c.cc.Invoke(ctx, FacilityService_ListFacility_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *facilityServiceClient) GetFacility(ctx context.Context, in *GetFacilityRequest, opts ...grpc.CallOption) (*GetFacilityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFacilityResponse)
	err := c.cc.Invoke(ctx, FacilityService_GetFacility_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FacilityServiceServer is the server API for FacilityService service.
// All implementations must embed UnimplementedFacilityServiceServer
// for forward compatibility.
type FacilityServiceServer interface {
	CreateFacility(context.Context, *CreateFacilityRequest) (*CreateFacilityResponse, error)
	UpdateFacility(context.Context, *UpdateFacilityRequest) (*UpdateFacilityResponse, error)
	DeleteFacility(context.Context, *DeleteFacilityRequest) (*DeleteFacilityResponse, error)
	ListFacility(context.Context, *ListFacilityRequest) (*ListFacilityResponse, error)
	GetFacility(context.Context, *GetFacilityRequest) (*GetFacilityResponse, error)
	mustEmbedUnimplementedFacilityServiceServer()
}

// UnimplementedFacilityServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFacilityServiceServer struct{}

func (UnimplementedFacilityServiceServer) CreateFacility(context.Context, *CreateFacilityRequest) (*CreateFacilityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFacility not implemented")
}
func (UnimplementedFacilityServiceServer) UpdateFacility(context.Context, *UpdateFacilityRequest) (*UpdateFacilityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFacility not implemented")
}
func (UnimplementedFacilityServiceServer) DeleteFacility(context.Context, *DeleteFacilityRequest) (*DeleteFacilityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFacility not implemented")
}
func (UnimplementedFacilityServiceServer) ListFacility(context.Context, *ListFacilityRequest) (*ListFacilityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFacility not implemented")
}
func (UnimplementedFacilityServiceServer) GetFacility(context.Context, *GetFacilityRequest) (*GetFacilityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFacility not implemented")
}
func (UnimplementedFacilityServiceServer) mustEmbedUnimplementedFacilityServiceServer() {}
func (UnimplementedFacilityServiceServer) testEmbeddedByValue()                         {}

// UnsafeFacilityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FacilityServiceServer will
// result in compilation errors.
type UnsafeFacilityServiceServer interface {
	mustEmbedUnimplementedFacilityServiceServer()
}

func RegisterFacilityServiceServer(s grpc.ServiceRegistrar, srv FacilityServiceServer) {
	// If the following call pancis, it indicates UnimplementedFacilityServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FacilityService_ServiceDesc, srv)
}

func _FacilityService_CreateFacility_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFacilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FacilityServiceServer).CreateFacility(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FacilityService_CreateFacility_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FacilityServiceServer).CreateFacility(ctx, req.(*CreateFacilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FacilityService_UpdateFacility_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFacilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FacilityServiceServer).UpdateFacility(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FacilityService_UpdateFacility_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FacilityServiceServer).UpdateFacility(ctx, req.(*UpdateFacilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FacilityService_DeleteFacility_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFacilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FacilityServiceServer).DeleteFacility(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FacilityService_DeleteFacility_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FacilityServiceServer).DeleteFacility(ctx, req.(*DeleteFacilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FacilityService_ListFacility_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFacilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FacilityServiceServer).ListFacility(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FacilityService_ListFacility_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FacilityServiceServer).ListFacility(ctx, req.(*ListFacilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FacilityService_GetFacility_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFacilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FacilityServiceServer).GetFacility(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FacilityService_GetFacility_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FacilityServiceServer).GetFacility(ctx, req.(*GetFacilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FacilityService_ServiceDesc is the grpc.ServiceDesc for FacilityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FacilityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "facility.FacilityService",
	HandlerType: (*FacilityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateFacility",
			Handler:    _FacilityService_CreateFacility_Handler,
		},
		{
			MethodName: "UpdateFacility",
			Handler:    _FacilityService_UpdateFacility_Handler,
		},
		{
			MethodName: "DeleteFacility",
			Handler:    _FacilityService_DeleteFacility_Handler,
		},
		{
			MethodName: "ListFacility",
			Handler:    _FacilityService_ListFacility_Handler,
		},
		{
			MethodName: "GetFacility",
			Handler:    _FacilityService_GetFacility_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "facility.proto",
}
