// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: gym.proto

package genprotos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateGymRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Longtitude    float32 `protobuf:"fixed32,1,opt,name=longtitude,proto3" json:"longtitude,omitempty"`
	Name          string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Location      string  `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	ContactNumber string  `protobuf:"bytes,4,opt,name=contact_number,json=contactNumber,proto3" json:"contact_number,omitempty"`
	Latitude      float32 `protobuf:"fixed32,5,opt,name=latitude,proto3" json:"latitude,omitempty"`
	TypeSport     string  `protobuf:"bytes,6,opt,name=type_sport,json=typeSport,proto3" json:"type_sport,omitempty"`
	TypeGender    string  `protobuf:"bytes,7,opt,name=type_gender,json=typeGender,proto3" json:"type_gender,omitempty"`
	OwnerId       string  `protobuf:"bytes,8,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
}

func (x *CreateGymRequest) Reset() {
	*x = CreateGymRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gym_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGymRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGymRequest) ProtoMessage() {}

func (x *CreateGymRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gym_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGymRequest.ProtoReflect.Descriptor instead.
func (*CreateGymRequest) Descriptor() ([]byte, []int) {
	return file_gym_proto_rawDescGZIP(), []int{0}
}

func (x *CreateGymRequest) GetLongtitude() float32 {
	if x != nil {
		return x.Longtitude
	}
	return 0
}

func (x *CreateGymRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateGymRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *CreateGymRequest) GetContactNumber() string {
	if x != nil {
		return x.ContactNumber
	}
	return ""
}

func (x *CreateGymRequest) GetLatitude() float32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *CreateGymRequest) GetTypeSport() string {
	if x != nil {
		return x.TypeSport
	}
	return ""
}

func (x *CreateGymRequest) GetTypeGender() string {
	if x != nil {
		return x.TypeGender
	}
	return ""
}

func (x *CreateGymRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

type CreateGymResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateGymResponse) Reset() {
	*x = CreateGymResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gym_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGymResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGymResponse) ProtoMessage() {}

func (x *CreateGymResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gym_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGymResponse.ProtoReflect.Descriptor instead.
func (*CreateGymResponse) Descriptor() ([]byte, []int) {
	return file_gym_proto_rawDescGZIP(), []int{1}
}

type UpdateGymRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Longtitude    float32 `protobuf:"fixed32,1,opt,name=longtitude,proto3" json:"longtitude,omitempty"`
	Name          string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Location      string  `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	ContactNumber string  `protobuf:"bytes,4,opt,name=contact_number,json=contactNumber,proto3" json:"contact_number,omitempty"`
	Latitude      float32 `protobuf:"fixed32,5,opt,name=latitude,proto3" json:"latitude,omitempty"`
	TypeSport     string  `protobuf:"bytes,6,opt,name=type_sport,json=typeSport,proto3" json:"type_sport,omitempty"`
	TypeGender    string  `protobuf:"bytes,7,opt,name=type_gender,json=typeGender,proto3" json:"type_gender,omitempty"`
	Id            string  `protobuf:"bytes,8,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId       string  `protobuf:"bytes,9,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
}

func (x *UpdateGymRequest) Reset() {
	*x = UpdateGymRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gym_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateGymRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGymRequest) ProtoMessage() {}

func (x *UpdateGymRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gym_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGymRequest.ProtoReflect.Descriptor instead.
func (*UpdateGymRequest) Descriptor() ([]byte, []int) {
	return file_gym_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateGymRequest) GetLongtitude() float32 {
	if x != nil {
		return x.Longtitude
	}
	return 0
}

func (x *UpdateGymRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateGymRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *UpdateGymRequest) GetContactNumber() string {
	if x != nil {
		return x.ContactNumber
	}
	return ""
}

func (x *UpdateGymRequest) GetLatitude() float32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *UpdateGymRequest) GetTypeSport() string {
	if x != nil {
		return x.TypeSport
	}
	return ""
}

func (x *UpdateGymRequest) GetTypeGender() string {
	if x != nil {
		return x.TypeGender
	}
	return ""
}

func (x *UpdateGymRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateGymRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

type UpdateGymResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateGymResponse) Reset() {
	*x = UpdateGymResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gym_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateGymResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGymResponse) ProtoMessage() {}

func (x *UpdateGymResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gym_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGymResponse.ProtoReflect.Descriptor instead.
func (*UpdateGymResponse) Descriptor() ([]byte, []int) {
	return file_gym_proto_rawDescGZIP(), []int{3}
}

type DeleteGymRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteGymRequest) Reset() {
	*x = DeleteGymRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gym_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteGymRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGymRequest) ProtoMessage() {}

func (x *DeleteGymRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gym_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGymRequest.ProtoReflect.Descriptor instead.
func (*DeleteGymRequest) Descriptor() ([]byte, []int) {
	return file_gym_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteGymRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteGymResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteGymResponse) Reset() {
	*x = DeleteGymResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gym_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteGymResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGymResponse) ProtoMessage() {}

func (x *DeleteGymResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gym_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGymResponse.ProtoReflect.Descriptor instead.
func (*DeleteGymResponse) Descriptor() ([]byte, []int) {
	return file_gym_proto_rawDescGZIP(), []int{5}
}

type GetGymRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetGymRequest) Reset() {
	*x = GetGymRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gym_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGymRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGymRequest) ProtoMessage() {}

func (x *GetGymRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gym_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGymRequest.ProtoReflect.Descriptor instead.
func (*GetGymRequest) Descriptor() ([]byte, []int) {
	return file_gym_proto_rawDescGZIP(), []int{6}
}

func (x *GetGymRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetGymResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Longtitude    float32 `protobuf:"fixed32,1,opt,name=longtitude,proto3" json:"longtitude,omitempty"`
	Name          string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Location      string  `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	ContactNumber string  `protobuf:"bytes,4,opt,name=contact_number,json=contactNumber,proto3" json:"contact_number,omitempty"`
	Latitude      float32 `protobuf:"fixed32,5,opt,name=latitude,proto3" json:"latitude,omitempty"`
	TypeSport     string  `protobuf:"bytes,6,opt,name=type_sport,json=typeSport,proto3" json:"type_sport,omitempty"`
	TypeGender    string  `protobuf:"bytes,7,opt,name=type_gender,json=typeGender,proto3" json:"type_gender,omitempty"`
	Id            string  `protobuf:"bytes,8,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId       string  `protobuf:"bytes,9,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
}

func (x *GetGymResponse) Reset() {
	*x = GetGymResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gym_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGymResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGymResponse) ProtoMessage() {}

func (x *GetGymResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gym_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGymResponse.ProtoReflect.Descriptor instead.
func (*GetGymResponse) Descriptor() ([]byte, []int) {
	return file_gym_proto_rawDescGZIP(), []int{7}
}

func (x *GetGymResponse) GetLongtitude() float32 {
	if x != nil {
		return x.Longtitude
	}
	return 0
}

func (x *GetGymResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetGymResponse) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *GetGymResponse) GetContactNumber() string {
	if x != nil {
		return x.ContactNumber
	}
	return ""
}

func (x *GetGymResponse) GetLatitude() float32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *GetGymResponse) GetTypeSport() string {
	if x != nil {
		return x.TypeSport
	}
	return ""
}

func (x *GetGymResponse) GetTypeGender() string {
	if x != nil {
		return x.TypeGender
	}
	return ""
}

func (x *GetGymResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetGymResponse) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

type ListGymRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page       int32  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Name       string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Location   string `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	TypeSport  string `protobuf:"bytes,4,opt,name=type_sport,json=typeSport,proto3" json:"type_sport,omitempty"`
	TypeGender string `protobuf:"bytes,5,opt,name=type_gender,json=typeGender,proto3" json:"type_gender,omitempty"`
}

func (x *ListGymRequest) Reset() {
	*x = ListGymRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gym_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListGymRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGymRequest) ProtoMessage() {}

func (x *ListGymRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gym_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGymRequest.ProtoReflect.Descriptor instead.
func (*ListGymRequest) Descriptor() ([]byte, []int) {
	return file_gym_proto_rawDescGZIP(), []int{8}
}

func (x *ListGymRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListGymRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListGymRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *ListGymRequest) GetTypeSport() string {
	if x != nil {
		return x.TypeSport
	}
	return ""
}

func (x *ListGymRequest) GetTypeGender() string {
	if x != nil {
		return x.TypeGender
	}
	return ""
}

type ListGymResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gym []*GetGymResponse `protobuf:"bytes,1,rep,name=gym,proto3" json:"gym,omitempty"`
}

func (x *ListGymResponse) Reset() {
	*x = ListGymResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gym_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListGymResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGymResponse) ProtoMessage() {}

func (x *ListGymResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gym_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGymResponse.ProtoReflect.Descriptor instead.
func (*ListGymResponse) Descriptor() ([]byte, []int) {
	return file_gym_proto_rawDescGZIP(), []int{9}
}

func (x *ListGymResponse) GetGym() []*GetGymResponse {
	if x != nil {
		return x.Gym
	}
	return nil
}

var File_gym_proto protoreflect.FileDescriptor

var file_gym_proto_rawDesc = []byte{
	0x0a, 0x09, 0x67, 0x79, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x67, 0x79, 0x6d,
	0x22, 0x80, 0x02, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x79, 0x6d, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x6c, 0x6f, 0x6e, 0x67, 0x74, 0x69, 0x74,
	0x75, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0a, 0x6c, 0x6f, 0x6e, 0x67, 0x74,
	0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74,
	0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63,
	0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08,
	0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08,
	0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x79, 0x70, 0x65,
	0x5f, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x79,
	0x70, 0x65, 0x53, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x79, 0x70, 0x65, 0x5f,
	0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x79,
	0x70, 0x65, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x77, 0x6e, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x77, 0x6e, 0x65,
	0x72, 0x49, 0x64, 0x22, 0x13, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x79, 0x6d,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x90, 0x02, 0x0a, 0x10, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x47, 0x79, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a,
	0x0a, 0x6c, 0x6f, 0x6e, 0x67, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x0a, 0x6c, 0x6f, 0x6e, 0x67, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x25, 0x0a,
	0x0e, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65,
	0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x79, 0x70, 0x65, 0x53, 0x70, 0x6f, 0x72, 0x74, 0x12,
	0x1f, 0x0a, 0x0b, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x79, 0x70, 0x65, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x19, 0x0a, 0x08, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x22, 0x13, 0x0a, 0x11, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x79, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x22, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x47, 0x79, 0x6d, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x13, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x47, 0x79,
	0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1f, 0x0a, 0x0d, 0x47, 0x65, 0x74,
	0x47, 0x79, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x8e, 0x02, 0x0a, 0x0e, 0x47,
	0x65, 0x74, 0x47, 0x79, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a,
	0x0a, 0x6c, 0x6f, 0x6e, 0x67, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x0a, 0x6c, 0x6f, 0x6e, 0x67, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x25, 0x0a,
	0x0e, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65,
	0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x79, 0x70, 0x65, 0x53, 0x70, 0x6f, 0x72, 0x74, 0x12,
	0x1f, 0x0a, 0x0b, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x79, 0x70, 0x65, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x19, 0x0a, 0x08, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x22, 0x94, 0x01, 0x0a, 0x0e,
	0x4c, 0x69, 0x73, 0x74, 0x47, 0x79, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61,
	0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x73, 0x70, 0x6f, 0x72, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x79, 0x70, 0x65, 0x53, 0x70, 0x6f, 0x72,
	0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x79, 0x70, 0x65, 0x47, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x22, 0x38, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x79, 0x6d, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x03, 0x67, 0x79, 0x6d, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x13, 0x2e, 0x67, 0x79, 0x6d, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x79, 0x6d, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x03, 0x67, 0x79, 0x6d, 0x32, 0xb3, 0x02, 0x0a,
	0x0a, 0x47, 0x79, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3c, 0x0a, 0x09, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x79, 0x6d, 0x12, 0x15, 0x2e, 0x67, 0x79, 0x6d, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x79, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x16, 0x2e, 0x67, 0x79, 0x6d, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x79, 0x6d, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3c, 0x0a, 0x09, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x47, 0x79, 0x6d, 0x12, 0x15, 0x2e, 0x67, 0x79, 0x6d, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x47, 0x79, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e,
	0x67, 0x79, 0x6d, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x79, 0x6d, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3c, 0x0a, 0x09, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x47, 0x79, 0x6d, 0x12, 0x15, 0x2e, 0x67, 0x79, 0x6d, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x47, 0x79, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x79,
	0x6d, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x47, 0x79, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x36, 0x0a, 0x07, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x79, 0x6d,
	0x12, 0x13, 0x2e, 0x67, 0x79, 0x6d, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x79, 0x6d, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x67, 0x79, 0x6d, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x47, 0x79, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x33, 0x0a,
	0x06, 0x47, 0x65, 0x74, 0x47, 0x79, 0x6d, 0x12, 0x12, 0x2e, 0x67, 0x79, 0x6d, 0x2e, 0x47, 0x65,
	0x74, 0x47, 0x79, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x67, 0x79,
	0x6d, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x79, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x42, 0x0c, 0x5a, 0x0a, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gym_proto_rawDescOnce sync.Once
	file_gym_proto_rawDescData = file_gym_proto_rawDesc
)

func file_gym_proto_rawDescGZIP() []byte {
	file_gym_proto_rawDescOnce.Do(func() {
		file_gym_proto_rawDescData = protoimpl.X.CompressGZIP(file_gym_proto_rawDescData)
	})
	return file_gym_proto_rawDescData
}

var file_gym_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_gym_proto_goTypes = []any{
	(*CreateGymRequest)(nil),  // 0: gym.CreateGymRequest
	(*CreateGymResponse)(nil), // 1: gym.CreateGymResponse
	(*UpdateGymRequest)(nil),  // 2: gym.UpdateGymRequest
	(*UpdateGymResponse)(nil), // 3: gym.UpdateGymResponse
	(*DeleteGymRequest)(nil),  // 4: gym.DeleteGymRequest
	(*DeleteGymResponse)(nil), // 5: gym.DeleteGymResponse
	(*GetGymRequest)(nil),     // 6: gym.GetGymRequest
	(*GetGymResponse)(nil),    // 7: gym.GetGymResponse
	(*ListGymRequest)(nil),    // 8: gym.ListGymRequest
	(*ListGymResponse)(nil),   // 9: gym.ListGymResponse
}
var file_gym_proto_depIdxs = []int32{
	7, // 0: gym.ListGymResponse.gym:type_name -> gym.GetGymResponse
	0, // 1: gym.GymService.CreateGym:input_type -> gym.CreateGymRequest
	2, // 2: gym.GymService.UpdateGym:input_type -> gym.UpdateGymRequest
	4, // 3: gym.GymService.DeleteGym:input_type -> gym.DeleteGymRequest
	8, // 4: gym.GymService.ListGym:input_type -> gym.ListGymRequest
	6, // 5: gym.GymService.GetGym:input_type -> gym.GetGymRequest
	1, // 6: gym.GymService.CreateGym:output_type -> gym.CreateGymResponse
	3, // 7: gym.GymService.UpdateGym:output_type -> gym.UpdateGymResponse
	5, // 8: gym.GymService.DeleteGym:output_type -> gym.DeleteGymResponse
	9, // 9: gym.GymService.ListGym:output_type -> gym.ListGymResponse
	7, // 10: gym.GymService.GetGym:output_type -> gym.GetGymResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_gym_proto_init() }
func file_gym_proto_init() {
	if File_gym_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gym_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CreateGymRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gym_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CreateGymResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gym_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateGymRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gym_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateGymResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gym_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteGymRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gym_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteGymResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gym_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*GetGymRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gym_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*GetGymResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gym_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*ListGymRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gym_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*ListGymResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gym_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gym_proto_goTypes,
		DependencyIndexes: file_gym_proto_depIdxs,
		MessageInfos:      file_gym_proto_msgTypes,
	}.Build()
	File_gym_proto = out.File
	file_gym_proto_rawDesc = nil
	file_gym_proto_goTypes = nil
	file_gym_proto_depIdxs = nil
}
