// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: unique.proto

package genprotos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateUniqueRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SportHallsId string `protobuf:"bytes,1,opt,name=sport_halls_id,json=sportHallsId,proto3" json:"sport_halls_id,omitempty"`
	FacilityId   string `protobuf:"bytes,2,opt,name=facility_id,json=facilityId,proto3" json:"facility_id,omitempty"`
	Count        int32  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *CreateUniqueRequest) Reset() {
	*x = CreateUniqueRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_unique_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUniqueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUniqueRequest) ProtoMessage() {}

func (x *CreateUniqueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_unique_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUniqueRequest.ProtoReflect.Descriptor instead.
func (*CreateUniqueRequest) Descriptor() ([]byte, []int) {
	return file_unique_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUniqueRequest) GetSportHallsId() string {
	if x != nil {
		return x.SportHallsId
	}
	return ""
}

func (x *CreateUniqueRequest) GetFacilityId() string {
	if x != nil {
		return x.FacilityId
	}
	return ""
}

func (x *CreateUniqueRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type CreateUniqueResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateUniqueResponse) Reset() {
	*x = CreateUniqueResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_unique_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUniqueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUniqueResponse) ProtoMessage() {}

func (x *CreateUniqueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_unique_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUniqueResponse.ProtoReflect.Descriptor instead.
func (*CreateUniqueResponse) Descriptor() ([]byte, []int) {
	return file_unique_proto_rawDescGZIP(), []int{1}
}

type UpdateUniqueRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SportHallsId string `protobuf:"bytes,1,opt,name=sport_halls_id,json=sportHallsId,proto3" json:"sport_halls_id,omitempty"`
	FacilityId   string `protobuf:"bytes,2,opt,name=facility_id,json=facilityId,proto3" json:"facility_id,omitempty"`
	Count        int32  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Id           string `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *UpdateUniqueRequest) Reset() {
	*x = UpdateUniqueRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_unique_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateUniqueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUniqueRequest) ProtoMessage() {}

func (x *UpdateUniqueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_unique_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUniqueRequest.ProtoReflect.Descriptor instead.
func (*UpdateUniqueRequest) Descriptor() ([]byte, []int) {
	return file_unique_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateUniqueRequest) GetSportHallsId() string {
	if x != nil {
		return x.SportHallsId
	}
	return ""
}

func (x *UpdateUniqueRequest) GetFacilityId() string {
	if x != nil {
		return x.FacilityId
	}
	return ""
}

func (x *UpdateUniqueRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *UpdateUniqueRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateUniqueResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateUniqueResponse) Reset() {
	*x = UpdateUniqueResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_unique_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateUniqueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUniqueResponse) ProtoMessage() {}

func (x *UpdateUniqueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_unique_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUniqueResponse.ProtoReflect.Descriptor instead.
func (*UpdateUniqueResponse) Descriptor() ([]byte, []int) {
	return file_unique_proto_rawDescGZIP(), []int{3}
}

type DeleteUniqueRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteUniqueRequest) Reset() {
	*x = DeleteUniqueRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_unique_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteUniqueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUniqueRequest) ProtoMessage() {}

func (x *DeleteUniqueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_unique_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUniqueRequest.ProtoReflect.Descriptor instead.
func (*DeleteUniqueRequest) Descriptor() ([]byte, []int) {
	return file_unique_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteUniqueRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteUniqueResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteUniqueResponse) Reset() {
	*x = DeleteUniqueResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_unique_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteUniqueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUniqueResponse) ProtoMessage() {}

func (x *DeleteUniqueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_unique_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUniqueResponse.ProtoReflect.Descriptor instead.
func (*DeleteUniqueResponse) Descriptor() ([]byte, []int) {
	return file_unique_proto_rawDescGZIP(), []int{5}
}

type GetUniqueRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetUniqueRequest) Reset() {
	*x = GetUniqueRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_unique_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUniqueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUniqueRequest) ProtoMessage() {}

func (x *GetUniqueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_unique_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUniqueRequest.ProtoReflect.Descriptor instead.
func (*GetUniqueRequest) Descriptor() ([]byte, []int) {
	return file_unique_proto_rawDescGZIP(), []int{6}
}

func (x *GetUniqueRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetUniqueResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SportHallsId string `protobuf:"bytes,1,opt,name=sport_halls_id,json=sportHallsId,proto3" json:"sport_halls_id,omitempty"`
	FacilityId   string `protobuf:"bytes,2,opt,name=facility_id,json=facilityId,proto3" json:"facility_id,omitempty"`
	Count        int32  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Id           string `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetUniqueResponse) Reset() {
	*x = GetUniqueResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_unique_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUniqueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUniqueResponse) ProtoMessage() {}

func (x *GetUniqueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_unique_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUniqueResponse.ProtoReflect.Descriptor instead.
func (*GetUniqueResponse) Descriptor() ([]byte, []int) {
	return file_unique_proto_rawDescGZIP(), []int{7}
}

func (x *GetUniqueResponse) GetSportHallsId() string {
	if x != nil {
		return x.SportHallsId
	}
	return ""
}

func (x *GetUniqueResponse) GetFacilityId() string {
	if x != nil {
		return x.FacilityId
	}
	return ""
}

func (x *GetUniqueResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GetUniqueResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListUniqueRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
}

func (x *ListUniqueRequest) Reset() {
	*x = ListUniqueRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_unique_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListUniqueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUniqueRequest) ProtoMessage() {}

func (x *ListUniqueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_unique_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUniqueRequest.ProtoReflect.Descriptor instead.
func (*ListUniqueRequest) Descriptor() ([]byte, []int) {
	return file_unique_proto_rawDescGZIP(), []int{8}
}

func (x *ListUniqueRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type ListUniquesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uniques []*GetUniqueResponse `protobuf:"bytes,1,rep,name=uniques,proto3" json:"uniques,omitempty"`
}

func (x *ListUniquesResponse) Reset() {
	*x = ListUniquesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_unique_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListUniquesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUniquesResponse) ProtoMessage() {}

func (x *ListUniquesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_unique_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUniquesResponse.ProtoReflect.Descriptor instead.
func (*ListUniquesResponse) Descriptor() ([]byte, []int) {
	return file_unique_proto_rawDescGZIP(), []int{9}
}

func (x *ListUniquesResponse) GetUniques() []*GetUniqueResponse {
	if x != nil {
		return x.Uniques
	}
	return nil
}

var File_unique_proto protoreflect.FileDescriptor

var file_unique_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x22, 0x72, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a,
	0x0e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x68, 0x61, 0x6c, 0x6c, 0x73, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x48, 0x61, 0x6c, 0x6c,
	0x73, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x61, 0x63, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x66, 0x61, 0x63, 0x69, 0x6c, 0x69,
	0x74, 0x79, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x16, 0x0a, 0x14, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x82, 0x01, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x6e, 0x69,
	0x71, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x0e, 0x73, 0x70,
	0x6f, 0x72, 0x74, 0x5f, 0x68, 0x61, 0x6c, 0x6c, 0x73, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x48, 0x61, 0x6c, 0x6c, 0x73, 0x49, 0x64,
	0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x61, 0x63, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x66, 0x61, 0x63, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x49,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x16, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x25, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x16, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x22,
	0x0a, 0x10, 0x47, 0x65, 0x74, 0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x80, 0x01, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x55, 0x6e, 0x69, 0x71, 0x75, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x0e, 0x73, 0x70, 0x6f, 0x72,
	0x74, 0x5f, 0x68, 0x61, 0x6c, 0x6c, 0x73, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x48, 0x61, 0x6c, 0x6c, 0x73, 0x49, 0x64, 0x12, 0x1f,
	0x0a, 0x0b, 0x66, 0x61, 0x63, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x66, 0x61, 0x63, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x27, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x55, 0x6e, 0x69,
	0x71, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x22, 0x4a,
	0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x07, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x2e,
	0x47, 0x65, 0x74, 0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x52, 0x07, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x73, 0x32, 0x82, 0x03, 0x0a, 0x0d, 0x55,
	0x6e, 0x69, 0x71, 0x75, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4b, 0x0a, 0x0c,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x12, 0x1b, 0x2e, 0x75,
	0x6e, 0x69, 0x71, 0x75, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x6e, 0x69, 0x71,
	0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x75, 0x6e, 0x69, 0x71,
	0x75, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4b, 0x0a, 0x0c, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x12, 0x1b, 0x2e, 0x75, 0x6e, 0x69, 0x71,
	0x75, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4b, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x12, 0x1b, 0x2e, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74, 0x55, 0x6e, 0x69, 0x71, 0x75,
	0x65, 0x12, 0x19, 0x2e, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x55,
	0x6e, 0x69, 0x71, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x75,
	0x6e, 0x69, 0x71, 0x75, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x55, 0x6e, 0x69, 0x71, 0x75, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x42, 0x0a, 0x09, 0x47,
	0x65, 0x74, 0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x12, 0x18, 0x2e, 0x75, 0x6e, 0x69, 0x71, 0x75,
	0x65, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x19, 0x2e, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x55,
	0x6e, 0x69, 0x71, 0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x0c, 0x5a, 0x0a, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_unique_proto_rawDescOnce sync.Once
	file_unique_proto_rawDescData = file_unique_proto_rawDesc
)

func file_unique_proto_rawDescGZIP() []byte {
	file_unique_proto_rawDescOnce.Do(func() {
		file_unique_proto_rawDescData = protoimpl.X.CompressGZIP(file_unique_proto_rawDescData)
	})
	return file_unique_proto_rawDescData
}

var file_unique_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_unique_proto_goTypes = []any{
	(*CreateUniqueRequest)(nil),  // 0: unique.CreateUniqueRequest
	(*CreateUniqueResponse)(nil), // 1: unique.CreateUniqueResponse
	(*UpdateUniqueRequest)(nil),  // 2: unique.UpdateUniqueRequest
	(*UpdateUniqueResponse)(nil), // 3: unique.UpdateUniqueResponse
	(*DeleteUniqueRequest)(nil),  // 4: unique.DeleteUniqueRequest
	(*DeleteUniqueResponse)(nil), // 5: unique.DeleteUniqueResponse
	(*GetUniqueRequest)(nil),     // 6: unique.GetUniqueRequest
	(*GetUniqueResponse)(nil),    // 7: unique.GetUniqueResponse
	(*ListUniqueRequest)(nil),    // 8: unique.ListUniqueRequest
	(*ListUniquesResponse)(nil),  // 9: unique.ListUniquesResponse
}
var file_unique_proto_depIdxs = []int32{
	7, // 0: unique.ListUniquesResponse.uniques:type_name -> unique.GetUniqueResponse
	0, // 1: unique.UniqueService.CreateUnique:input_type -> unique.CreateUniqueRequest
	2, // 2: unique.UniqueService.UpdateUnique:input_type -> unique.UpdateUniqueRequest
	4, // 3: unique.UniqueService.DeleteUnique:input_type -> unique.DeleteUniqueRequest
	8, // 4: unique.UniqueService.ListUnique:input_type -> unique.ListUniqueRequest
	6, // 5: unique.UniqueService.GetUnique:input_type -> unique.GetUniqueRequest
	1, // 6: unique.UniqueService.CreateUnique:output_type -> unique.CreateUniqueResponse
	3, // 7: unique.UniqueService.UpdateUnique:output_type -> unique.UpdateUniqueResponse
	5, // 8: unique.UniqueService.DeleteUnique:output_type -> unique.DeleteUniqueResponse
	9, // 9: unique.UniqueService.ListUnique:output_type -> unique.ListUniquesResponse
	7, // 10: unique.UniqueService.GetUnique:output_type -> unique.GetUniqueResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_unique_proto_init() }
func file_unique_proto_init() {
	if File_unique_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_unique_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CreateUniqueRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_unique_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CreateUniqueResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_unique_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateUniqueRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_unique_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateUniqueResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_unique_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteUniqueRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_unique_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteUniqueResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_unique_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*GetUniqueRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_unique_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*GetUniqueResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_unique_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*ListUniqueRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_unique_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*ListUniquesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_unique_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_unique_proto_goTypes,
		DependencyIndexes: file_unique_proto_depIdxs,
		MessageInfos:      file_unique_proto_msgTypes,
	}.Build()
	File_unique_proto = out.File
	file_unique_proto_rawDesc = nil
	file_unique_proto_goTypes = nil
	file_unique_proto_depIdxs = nil
}
